name: rss bot

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install requests beautifulsoup4
      - run: python generate.py
      - run: |
          git config --global user.name "rss-bot"
          git config --global user.email "rss@bot.com"
          git add feed.xml
          git commit -m "rss update" || echo "no change"
          git push
